//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.TripBookings = new HashSet<TripBooking>();
        }
    
        public int Id { get; set; }
        public string RefId { get; set; }
        public int CustomerId { get; set; }
        public int BusTimeId { get; set; }
        public int SeatCount { get; set; }
        public System.DateTime Date { get; set; }
        public int PaymentStatus { get; set; }
        public bool IsActive { get; set; }
        public int StartLocation { get; set; }
        public int EndLocation { get; set; }
    
        public virtual BusTime BusTime { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripBooking> TripBookings { get; set; }
    }
}
