//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDevice
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int DeviceId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
