//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int Id { get; set; }
        public int BusId { get; set; }
        public string Number { get; set; }
        public int TypeId { get; set; }
        public int SideId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual SeatSide SeatSide { get; set; }
        public virtual SeatType SeatType { get; set; }
    }
}
